name: dwd_website
description: "A new Flutter website project for dartford web designs."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  all_lint_rules_community: ^0.0.3

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Snapchat-1336896579 (1).jpg
